### ISSUE TITLE
[Project] Unresolved questions

### ISSUE THREAD

**Issue by LHRaceIng** [Joni32do/NumSim#11]
* Why do f(), g() and rhs() in staggered are not supposed to be returnable as const like u(), v(), p()?
* Why  do we need uIBegin(), vIBegin() etc. in staggered grid? Isn't that always 0?

**Comment by Joni32do** [comment]
* staggeredGrid.uIBegin -> Sinnvoll gridsize gleich
* Features Benotung (ist es ratsam möglichst wenig von Template abzuweichen)
* Wann ist rechnen auf dem Server sinnvoll?

**Comment by Joni32do** [comment]
* Model Choice for $u^2$ with only one Upwind, Downwind point
