### ISSUE TITLE
Structural Problems

### ISSUE THREAD

**Issue by LHRaceIng** [Joni32do/NumSim#14]
I am not sure if we are initializing the size of rhs correctly in staggered grid StaggeredGrid. ATM we give it as many points as p has inside the domain but i think that rhs has less point because it is not calculated from u/v/p but f and g which themselves already only have points inside the domain. Or I am missing something

**Comment by Joni32do** [comment]
We can discuss this tomorrow, but shooting from the hip I think F,G are renormalized to the pressure position. I think this problem will reaove itself once we implement the Calculation and Solver #3
