### ISSUE TITLE
Index ist sehr schlecht gelöst (F und u) nicht kompatibel

### ISSUE THREAD

**Issue by Joni32do** [Joni32do/NumSim#18]
Unser Hauptfehler, den ich vermutlich in der restlichen Zeit heute nicht mehr beheben kann ist, dass wir mit index von z.B. $F$ nicht zu Index $u$ jonglieren können, sondern immer einen Umrechnungsfaktor brauchen.

Eine Lösung, wäre das minimal größere Grid für die 'kleineren Grids' einfach zu akzeptieren. Sonst muss man eine Umrechung einfügen

**Comment by Joni32do** [comment]
Wobei ne das stimmt gar nicht, ich glaub ich verstehe den Fehler doch noch nicht. F und u sind doch eigentlich gleich groß. Genau so wie G und v

Fest steht im ersten Zeitschritt machen wir hier etwas falsch

**Comment by LHRaceIng** [comment]
Okay ich werde es mir frühestens Sonntag angucken können. Was wäre das denn für ein Faktor? Wenn es hier zu aufwändig ist kannst du es mir/ uns am Sonntag erklären.
